DROP DATABASE IF EXISTS SISTEMA_VENTAS;
CREATE DATABASE SISTEMA_VENTAS;
USE SISTEMA_VENTAS;

DROP TABLE IF EXISTS CARGO;
CREATE TABLE CARGO
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    SALARIO DECIMAL(18 , 2) NOT NULL,
    PRIMARY KEY (CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS EMPLEADO;
CREATE TABLE EMPLEADO
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO VARCHAR(25) NOT NULL,
    CODIGO_CARGO INT NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    DUI VARCHAR(10) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DIRECCION VARCHAR(155) NOT NULL,
    USUARIO VARCHAR(25) NULL,
    CONTRASEÑA VARCHAR(25) NULL,
    TIPO VARCHAR(25) NULL,
    FOTOGRAFIA BLOB NULL,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_CARGO) REFERENCES CARGO(CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CATEGORIA;
CREATE TABLE CATEGORIA
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    DESCRIPCION VARCHAR(155) NULL,
    PRIMARY KEY (CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS PROVEEDOR;
CREATE TABLE PROVEEDOR
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(155) NULL,
    DIRECCION VARCHAR(155) NOT NULL,
    IMAGEN BLOB NULL,
    PRIMARY KEY (CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS COMPRA;
CREATE TABLE COMPRA
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    FECHA DATE NOT NULL,
    CODIGO_EMPLEADO INT NOT NULL,
    COMPROBANTE VARCHAR(10) NOT NULL,
    NUMERO_COMPROBANTE VARCHAR(10) NOT NULL,
    CODIGO_PROVEEDOR INT NOT NULL,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADO(CODIGO),
    FOREIGN KEY (CODIGO_PROVEEDOR) REFERENCES PROVEEDOR(CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    CODIGO_CATEGORIA INT NOT NULL,
    DESCRIPCION VARCHAR(155) NULL,
    IMAGEN BLOB NULL,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS DETALLE_COMPRA;
CREATE TABLE DETALLE_COMPRA
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    CODIGO_COMPRA INT NOT NULL,
    CODIGO_PRODUCTO INT NOT NULL,
    PRECIO_COMPRA DECIMAL(18 , 2) NOT NULL,
    PRECIO_VENTA DECIMAL(18 , 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_COMPRA) REFERENCES COMPRA(CODIGO),
    FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    FECHA DATE NOT NULL,
    CODIGO_EMPLEADO INT NOT NULL,
    COMPROBANTE VARCHAR(20) NOT NULL,
    NUMERO_COMPROBANTE VARCHAR(10) NOT NULL,
    ESTADO VARCHAR(10) NOT NULL,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS DETALLE_VENTA;
CREATE TABLE DETALLE_VENTA
(
    CODIGO INT AUTO_INCREMENT NOT NULL,
    CODIGO_VENTA INT NOT NULL,
    CODIGO_DETALLE_COMPRA INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(18 , 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_VENTA) REFERENCES VENTA(CODIGO),
    FOREIGN KEY (CODIGO_DETALLE_COMPRA) REFERENCES DETALLE_COMPRA(CODIGO)
)ENGINE=InnoDB;



